### ISSUE TITLE
GeoJSON fill color

### ISSUE THREAD

**Issue by taalas** [jperelli/osm-static-maps#16]
Is it possible to adjust the fill color used to display geojson polygons?

**Comment by jperelli** [comment]
@taalas That's actually a good feature, I'll work on that, probably on this weekend

**Comment by taalas** [comment]
Awesome! It would be great if the fill color could be evaluated per Feature (even in a FeatureCollection). Probably by allowing a property in Properties?

**Comment by jperelli** [comment]
@taalas done, I added a new global `style` option and per geojson feature `pathOptions` option that expects a path options object (see https://leafletjs.com/reference-1.6.0.html#path-option) for styling

Published in npm as v3.8.0

Let me know if that works!
