### ISSUE TITLE
Crash when adding very large polylines

### ISSUE THREAD

**Issue by paulsUsername** [jperelli/osm-static-maps#22]
I am getting the following crash when trying to add very large polylines:

```
code:"E2BIG"
errno:"E2BIG"
error:Error: spawnSync /bin/sh E2BIG
message:"spawnSync /bin/sh E2BIG"
output:null
path:"/bin/sh"
pid:79999
signal:null
```

Any advice?

**Comment by jperelli** [comment]
cool, mhh can you give an example for reproduction of this issue?

**Comment by jperelli** [comment]
I couldn't reproduce this, so if someone gives me a repro I'll look into it.
for the record tried with 20mb of world data, and it works just fine
![img2](https://user-images.githubusercontent.com/1418446/90299994-abfb7480-de98-11ea-9906-7a27062a21cd.png)

**Comment by jperelli** [comment]
also inspired me to open this issue https://github.com/jperelli/osm-static-maps/issues/23
