### ISSUE TITLE
Heroku app is offline

### ISSUE THREAD

**Issue by janbaykara** [jperelli/osm-static-maps#28]
Hiya, [this matrix of available services](https://wiki.openstreetmap.org/wiki/Static_map_images) says yours is healthy, but it looks like it's offline.

<img width="591" alt="Screenshot 2020-12-18 at 12 22 19" src="https://user-images.githubusercontent.com/237556/102614170-ae622980-412b-11eb-8a36-7d40ced780b1.png">

**Comment by jperelli** [comment]
Thanks, I fixed it here https://github.com/jperelli/osm-static-maps/commit/7c3330d7a23b4eb74c286688bc26bbe28c46f2b4

**Comment by binc0** [comment]
It would be great to add [Deploy to Heroku button](https://devcenter.heroku.com/articles/heroku-button) to reduce demo load as anyone could make his own server with just some clicks
