### ISSUE TITLE
Top-level declarations in .d.ts files

### ISSUE THREAD

**Issue by skde** [jperelli/osm-static-maps#29]
node_modules/osm-static-maps/src/lib.d.ts:141:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
`
function _default<T extends OsmStaticMapsOptions>(
`
This change helps:
https://github.com/jperelli/osm-static-maps/pull/30

**Comment by jperelli** [comment]
thanks, merged!
