### ISSUE TITLE
There is "Application error" in demo

### ISSUE THREAD

**Issue by ghost** [jperelli/osm-static-maps#31]
I am aware of that

> heroku server might be unstable because of too many requests being made to it

but http://osm-static-maps.herokuapp.com/ showing

```
 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail 
```

looks suspicious to me.

**Comment by nelsonlarocca** [comment]
All demos reach a page error !

**Comment by jperelli** [comment]
Heroku is no more available because of pricing
