### ISSUE TITLE
Application crashes without errors on import

### ISSUE THREAD

**Issue by fabdrol** [jperelli/osm-static-maps#39]
adding `import osmsm from 'osm-static-maps';` causes my application to crash immediately, without any error.

**Comment by jperelli** [comment]
Hi @fabdrol, could you give more information about how you structure your application, or give a minimal reproduction example?

**Comment by jperelli** [comment]
Ok, will close this. Reopen issue if you have the log of the crash. Or some more info than "my application crashes". It could be virtually infinite causes.
