### ISSUE TITLE
Trying to understand how to configure a Vector Tile Layer with the Style.json

### ISSUE THREAD

**Issue by techmavengeospatial** [jperelli/osm-static-maps#47]
are PBF/MVT Vector Tile Sources with stylesheets  (JSON) supported?

**Comment by jperelli** [comment]
Hi @techmavengeospatial!

Yes, you need to set the url to a style.json using the `-m` or `vectorserverUrl` parameter

It uses this library https://github.com/mapbox/mapbox-gl-leaflet
