### ISSUE TITLE
Broken demos.

### ISSUE THREAD

**Issue by sustained** [jperelli/osm-static-maps#7]
The demos are giving an application error.

**Comment by jperelli** [comment]
Hi @sustained Can you give more information on this one? what command are you running? what's the error? do you have a stack trace?

**Comment by sustained** [comment]
Your demos on Heroku are broken.

**Comment by jperelli** [comment]
@sustained I see it working now, can you see it?
I think that the heroku demo might be unstable because of too many requests being made to it. I'll add a note in the README. Feel free to reopen the issue if needed.

**Comment by sameersb** [comment]
Currently any request is giving the same error!

**Comment by jperelli** [comment]
A possible solution is trying to maintain the background browser open through requests as singleton. I'll try doing a singleton logic, It should also help when doing multiple queries in a for loop.

**Comment by MarkusTiede** [comment]
Same for me - the demo / instance still seems to be broken: is there any log / more information we can provide helping you to fix this?

**Comment by jperelli** [comment]
Basically I don't have monetary resources to pay for a dedicated server for this... so... It's being used too much...
I'll try to improve the performance of it by doing what I stated on the previous message, but it's going to happen again, unless I can get the money for a non-free server

**Comment by jperelli** [comment]
@MarkusTiede @sameersb @sustained please could you try now?

**Comment by MarkusTiede** [comment]
Now it's working again - thanks! Maybe https://github.com/sponsors could help you there?
