### ISSUE TITLE
Add marker icon option

### ISSUE THREAD

**Issue by jperelli** [jperelli/osm-static-maps#9]
Add option to set a different marker icon. Refer to how google static maps api does it.
 -  see this https://leafletjs.com/reference-1.6.0.html#icon
 - and here https://wiki.openstreetmap.org/wiki/Static_map_images#Comparison_Matrix

**Comment by czare** [comment]
Yeah, that would be great

**Comment by jperelli** [comment]
solved in 81785a4c2532870c2382e88ee145192c7788a82d, published in npm as v3.5.0 enjoy @czare!
